### ISSUE TITLE
Stock Codes

### ISSUE THREAD

**Issue by therealplayer** [harrytwigg/Viaduct-Trading212-Python-API#1]
Hello, thanks for making this. It's super helpful for stocks that you know the code for. Unfortunately, the method you implemented of finding the stock codes seems to be outdated. The url hits you with a "404 this page doesn't exist". Any tips for finding the stocks codes without that?

**Comment by therealplayer** [comment]
Ah, wait, obviously I'd find it now. The link https://live.trading212.com/rest/companies gets the job done.

**Comment by harrytwigg** [comment]
I will update it within a few days

Best wishes,
Harry Twigg

________________________________

**Comment by harrytwigg** [comment]
Let me know if there's anything else you'd like me to implement this project is far from finished

Best wishes,
Harry Twigg

________________________________

**Comment by harrytwigg** [comment]
Reopened as API seems to have been updated by Trading212

**Comment by harrytwigg** [comment]
The API endpoint was changed
